config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :movies, only: %i[index show]
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

# <div class="row justify-content-center">
# <div class="col-4">
#   <h1>Add a bookmark</h1>

#   <%= simple_form_for [@list, @bookmark] do |f| %>
#     <%= f.input :comment %>
#     <%= f.association :movie %>
#     <%= f.submit %>
#   <% end %>
# </div>
# </div>

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id, message: 'has already been bookmarked in this list' }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def index
  #   @bookmarks = Bookmark.all
  # end

  # def show
  #   @bookmark = bookmark.find(params[:id])
  # end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

def index
  # ?
  @movies = Movie.all
end

def show
  @movie = Movie.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class='container'>
  <h1>Lists Index</h1>
  <% @lists.each do |list| %>
    <div class="card-category">
      <h2><%= link_to list.name, list_path(list) %></h2>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <div class="container mt-3">
    <div class="form-inputs">
      <%= f.input :name %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <div class="row my-3 mx-6">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-12 col-md-4">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= bookmark.movie.poster_url %>')">
          <h2><%= bookmark.movie.title %></h2>
          <p><%= bookmark.comment %></p>
          <p><%= link_to '+', bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'card-remove-link' %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div>
    <%# <%= link_to "new bookmark", new_list_bookmark_path %>
    <div class="row justify-content-center">
      <div class="col-4">
        <h1>Add a bookmark</h1>

        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment %>
          <%= f.association :movie %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class='container'>
  <h1>Movies Index</h1>
  <% @movies.each do |movie| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= movie.poster_url %>')">
      <h2><%= movie.title %></h2>
      <ul>
        <li><%= movie.overview %></li>
        <li><%= movie.rating %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h1><%= @movie.title %></h1>
</div>